import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "./_components/Navbar";

import  {FormProvider}   from '../app/context/CandidateFormContext'
import {ClerkProvider} from "@clerk/nextjs"



export const metadata: Metadata = {
  title: "Find Job",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <Navbar/>
        <FormProvider>
        <TRPCReactProvider>{children}</TRPCReactProvider>
         </FormProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
